const CityArray = [
    //0
    [],
    //1 - آذربایجان شرقی
    [
        { label: 'تبریز', value: 1 },
        { label: 'آبش‌احمد', value: 438 },
        { label: 'آچاچی', value: 439 },
        { label: 'آذرشهر', value: 11 },
        { label: 'آقکند', value: 440 },
        { label: 'اربطان', value: 441 },
        { label: 'اسکو', value: 5 },
        { label: 'اهر', value: 6 },
        { label: 'ایلخچی', value: 442 },
        { label: 'باسمنج', value: 443 },
        { label: 'بخشایش', value: 444 },
        { label: 'بستان‌آباد', value: 12 },
        { label: 'بناب', value: 8 },
        { label: 'بناب مرند', value: 445 },
        { label: 'ترک', value: 446 },
        { label: 'ترکمانچای', value: 447 },
        { label: 'تسوج', value: 448 },
        { label: 'تیکمه‌داش', value: 449 },
        { label: 'تیمورلو', value: 450 },
        { label: 'جلفا', value: 15 },
        { label: 'جوان‌قلعه', value: 451 },
        { label: 'خاروانا', value: 452 },
        { label: 'خامنه', value: 453 },
        { label: 'خداجو', value: 454 },
        { label: 'خسروشاه', value: 455 },
        { label: 'خمارلو', value: 456 },
        { label: 'خواجه', value: 457 },
        { label: 'خوشه‌مهر', value: 458 },
        { label: 'داریان', value: 459 },
        { label: 'دوزدوزان', value: 460 },
        { label: 'دیزج حسین‌بیگ', value: 461 },
        { label: 'زرنق', value: 462 },
        { label: 'زنوز', value: 463 },
        { label: 'سراب', value: 9 },
        { label: 'سردرود', value: 465 },
        { label: 'سهند', value: 466 },
        { label: 'سیس', value: 467 },
        { label: 'سیه‌رود', value: 468 },
        { label: 'شبستر', value: 7 },
        { label: 'شربیان', value: 469 },
        { label: 'شرفخانه', value: 470 },
        { label: 'شندآباد', value: 471 },
        { label: 'صوفیان', value: 472 },
        { label: 'عاشقلو', value: 473 },
        { label: 'عجب‌شیر', value: 13 },
        { label: 'علیشاه', value: 474 },
        { label: 'قره‌آغاج', value: 475 },
        { label: 'کردکندی', value: 476 },
        { label: 'کشکسرای', value: 477 },
        { label: 'کلوانق', value: 478 },
        { label: 'کلیبر', value: 18 },
        { label: 'کوزه‌کنان', value: 479 },
        { label: 'گوگان', value: 480 },
        { label: 'لاریجان', value: 481 },
        { label: 'لیلان', value: 482 },
        { label: 'مبارک‌شهر', value: 483 },
        { label: 'مراغه', value: 2 },
        { label: 'مرند', value: 3 },
        { label: 'ملکان', value: 10 },
        { label: 'ممقان', value: 484 },
        { label: 'مهربان', value: 485 },
        { label: 'میانه', value: 4 },
        { label: 'نظرکهریزی', value: 486 },
        { label: 'وایقان', value: 487 },
        { label: 'ورزقان', value: 17 },
        { label: 'هادیشهر', value: 488 },
        { label: 'هریس', value: 14 },
        { label: 'هشترود', value: 16 },
        { label: 'هوراند', value: 489 },
        { label: 'یامچی', value: 490 },

    ],
    //2 - آذربایجان غربی
    [
        { label: 'ارومیه', value: 21 },
        { label: 'آواجیق', value: 519 },
        { label: 'اشنویه', value: 33 },
        { label: 'ایواوغلی', value: 513 },
        { label: 'باروق', value: 508 },
        { label: 'بازرگان', value: 496 },
        { label: 'بکتاش', value: 512 },
        { label: 'بوکان', value: 24 },
        { label: 'پلدشت', value: 37 },
        { label: 'پیرانشهر', value: 27 },
        { label: 'تازه‌شهر', value: 500 },
        { label: 'تازه‌کندنصرت‌آباد', value: 525 },
        { label: 'تکاب', value: 32 },
        { label: 'چهاربرج', value: 497 },
        { label: 'حاجیلار', value: 521 },
        { label: 'خلیفان', value: 524 },
        { label: 'خوی', value: 22 },
        { label: 'دیزج دیز', value: 503 },
        { label: 'ربط', value: 494 },
        { label: '	زرآباد', value: 523 },
        { label: 'سردشت', value: 29 },
        { label: 'سرو', value: 518 },
        { label: 'سلماس', value: 26 },
        { label: 'سیلوانه', value: 520 },
        { label: 'سیمینه', value: 522 },
        { label: 'سیه‌چشمه', value: 493 },
        { label: 'شاهین‌دژ', value: 31 },
        { label: 'شوط', value: 34 },
        { label: 'فیرورق', value: 499 },
        { label: 'قره‌ضیاءالدین', value: 491 },
        { label: 'قطور', value: 507 },
        { label: 'قوشچی', value: 515 },
        { label: 'کشاورز', value: 510 },
        { label: 'گوگ تپه', value: 504 },
        { label: 'لاجان', value: 509 },
        { label: 'ماکو', value: 30 },
        { label: 'محمدیار', value: 498 },
        { label: 'محمودآباد', value: 505 },
        { label: 'مرگنلر', value: 517 },
        { label: 'مهاباد', value: 25 },
        { label: 'میاندوآب', value: 23 },
        { label: 'میرآباد', value: 506 },
        { label: 'نازک علیا', value: 516 },
        { label: 'نالوس', value: 514 },
        { label: 'نقده', value: 28 },
        { label: 'نلاس', value: 501 },
        { label: 'نوشین‌شهر', value: 502 },
        { label: 'یولاگلدی', value: 511 },

    ],
    //3 - اردبیل
    [
        { label: 'اردبیل', value: 38 },
        { label: 'آبی‌بیگلو', value: 528 },
        { label: 'آراللو', value: 529 },
        { label: 'آلنی', value: 530 },
        { label: 'اسلام‌آباد', value: 531 },
        { label: 'اصلاندوز', value: 45 },
        { label: 'اولتان', value: 532 },
        { label: 'ایردموسی', value: 533 },
        { label: 'بابک شهر', value: 534 },
        { label: 'بیله‌سوار', value: 44 },
        { label: 'پارس‌آباد', value: 39 },
        { label: 'تازه‌کند انگوت', value: 535 },
        { label: 'ثمرین', value: 536 },
        { label: 'جعفرآباد', value: 526 },
        { label: 'خلخال', value: 41 },
        { label: 'رضی', value: 537 },
        { label: 'سرعین', value: 48 },
        { label: 'عنبران', value: 538 },
        { label: '	فخرآباد', value: 539 },
        { label: 'قصابه', value: 540 },
        { label: 'کلور', value: 541 },
        { label: 'کوراییم', value: 542 },
        { label: 'گرمی', value: 42 },
        { label: 'گیوی', value: 527 },
        { label: 'لاهرود', value: 543 },
        { label: 'مرادلو', value: 544 },
        { label: 'مشگین‌شهر', value: 40 },
        { label: 'مغانسر', value: 545 },
        { label: 'نمین', value: 43 },
        { label: 'نیر', value: 47 },
        { label: 'هشجین', value: 546 },
        { label: 'هیر', value: 547 },
    ],
    //4 - اصفهان
    [

        { label: 'اصفهان', value: 49 },
        { label: 'آران و بیدگل', value: 60 },
        { label: 'ابریشم', value: 548 },
        { label: 'ابوزیدآباد', value: 549 },
        { label: 'اردستان', value: 66 },
        { label: 'اژیه', value: 550 },
        { label: 'اشترجان', value: 551 },
        { label: 'اصغرآباد', value: 552 },
        { label: 'افوس', value: 553 },
        { label: 'انارک', value: 554 },
        { label: 'ایمان‌شهر', value: 555 },
        { label: 'بادرود', value: 556 },
        { label: 'باغ‌بهادران', value: 557 },
        { label: 'باغشاد', value: 558 },
        { label: 'بافران', value: 559 },
        { label: 'برزک', value: 560 },
        { label: 'برف‌انبار', value: 561 },
        { label: 'بوئین و میاندشت', value: 72 },
        { label: 'بوستان', value: 562 },
        { label: 'بهاران‌شهر', value: 563 },
        { label: 'بهارستان', value: 564 },
        { label: 'بیده', value: 565 },
        { label: 'پیربکران', value: 566 },
        { label: 'تودشک', value: 567 },
        { label: 'تیران', value: 63 },
        { label: 'جندق', value: 568 },
        { label: 'جوزدان', value: 569 },
        { label: 'جوشقان قالی', value: 570 },
        { label: 'چادگان', value: 71 },
        { label: 'چرمهین', value: 571 },
        { label: 'چمگردان', value: 572 },
        { label: 'حبیب‌آباد', value: 573 },
        { label: 'حسن‌آباد', value: 574 },
        { label: 'حنا', value: 575 },
        { label: 'خالدآباد', value: 576 },
        { label: 'خمینی‌شهر', value: 51 },
        { label: 'خوانسار', value: 70 },
        { label: 'خور', value: 73 },
        { label: 'خورزوق', value: 577 },
        { label: 'داران', value: 578 },
        { label: 'دامنه', value: 579 },
        { label: 'درچه', value: 580 },
        { label: 'دستگرد', value: 581 },
        { label: 'دولت‌آباد', value: 59 },
        { label: 'دهاقان', value: 69 },
        { label: 'ده‌سرخ', value: 582 },
        { label: 'دهق', value: 583 },
        { label: 'دیزیچه', value: 584 },
        { label: 'راوند', value: 585 },
        { label: 'رزوه', value: 586 },
        { label: 'رضوانشهر', value: 587 },
        { label: 'زازران', value: 588 },
        { label: 'زاینده‌رود', value: 589 },
        { label: 'زرین شهر', value: 53 },
        { label: 'زواره', value: 590 },
        { label: 'زیار', value: 591 },
        { label: 'زیباشهر', value: 592 },
        { label: 'سجزی', value: 593 },
        { label: 'سده لنجان', value: 594 },
        { label: 'سفیدشهر', value: 595 },
        { label: 'سمیرم', value: 62 },
        { label: 'سین', value: 596 },
        { label: 'شاپورآباد', value: 597 },
        { label: 'شاهین‌شهر', value: 55 },
        { label: 'شهرضا', value: 57 },
        { label: 'طاد', value: 598 },
        { label: 'طالخونچه', value: 599 },
        { label: 'طرق‌رود', value: 600 },
        { label: 'عسگران', value: 601 },
        { label: 'علویجه', value: 602 },
        { label: 'فتح‌آباد', value: 603 },
        { label: 'فرخی', value: 604 },
        { label: 'فریدون‌شهر', value: 68 },
        { label: 'فلاورجان', value: 54 },
        { label: 'فولادشهر', value: 605 },
        { label: 'قمصر', value: 606 },
        { label: 'قهجاورستان', value: 607 },
        { label: 'قهدریجان', value: 608 },
        { label: 'کاشان', value: 50 },
        { label: 'کامو و چوگان', value: 609 },
        { label: 'کرکوند', value: 610 },
        { label: 'کلیشاد و سودرجان', value: 611 },
        { label: 'کمشچه', value: 612 },
        { label: 'کمه', value: 613 },
        { label: 'کوشک', value: 614 },
        { label: 'کوهپایه', value: 615 },
        { label: 'کهریزسنگ', value: 616 },
        { label: 'گرگاب', value: 617 },
        { label: 'گزبرخوار', value: 618 },
        { label: 'گلپایگان', value: 61 },
        { label: 'گلدشت', value: 619 },
        { label: 'گلشن', value: 620 },
        { label: 'گلشهر', value: 621 },
        { label: 'گوگد', value: 622 },
        { label: 'لای بید', value: 623 },
        { label: 'مبارکه', value: 58 },
        { label: 'محمدآباد', value: 624 },
        { label: 'مشکات', value: 625 },
        { label: 'منظریه', value: 626 },
        { label: 'مهاباد', value: 627 },
        { label: 'میمه', value: 56 },
        { label: 'مینادشت', value: 628 },
        { label: 'نائین', value: 67 },
        { label: 'نجف‌آباد', value: 52 },
        { label: 'نصرآباد', value: 629 },
        { label: 'نطنز', value: 65 },
        { label: 'نوش‌آباد', value: 631 },
        { label: 'نیاسر', value: 632 },
        { label: 'نیک‌آباد', value: 633 },
        { label: 'ورزنه', value: 634 },
        { label: 'ورنامخواست', value: 635 },
        { label: 'وزوان', value: 636 },
        { label: 'ونک', value: 637 },
        { label: 'ویست', value: 638 },
        { label: 'هرند', value: 639 },
    ],
    //5 - البرز
    [

        { label: 'کرج', value: 74 },
        { label: 'آسارا', value: 640 },
        { label: 'اشتهارد', value: 78 },
        { label: 'پلنگ‌آباد', value: 641 },
        { label: 'تنکمان', value: 642 },
        { label: 'چهارباغ', value: 643 },
        { label: 'هشتگرد', value: 644 },
        { label: 'طالقان', value: 79 },
        { label: 'فردیس', value: 75 },
        { label: 'کمال‌شهر', value: 645 },
        { label: 'کوهسار', value: 646 },
        { label: 'گرمدره', value: 647 },
        { label: 'گلسار', value: 648 },
        { label: 'ماهدشت', value: 649 },
        { label: 'محمدشهر', value: 650 },
        { label: 'مشکین‌دشت', value: 651 },
        { label: 'نظرآباد', value: 77 },
    ],
    //6 - ایلام
    [

        { label: 'ایلام', value: 80 },
        { label: 'ارکواز', value: 652 },
        { label: 'ایوان', value: 83 },
        { label: 'آبدانان', value: 84 },
        { label: 'آسمان‌آباد', value: 635 },
        { label: 'بدره', value: 88 },
        { label: 'بلاوه', value: 654 },
        { label: 'پهله', value: 655 },
        { label: 'توحید', value: 656 },
        { label: 'جعفرآباد', value: 657 },
        { label: 'چشمه شیرین', value: 658 },
        { label: 'چوار', value: 659 },
        { label: 'دره شهر', value: 660 },
        { label: 'دلگشا', value: 661 },
        { label: 'دهلران', value: 81 },
        { label: 'زرنه', value: 663 },
        { label: 'سراب‌باغ', value: 664 },
        { label: 'سرابله', value: 665 },
        { label: 'شباب', value: 666 },
        { label: 'صالح‌آباد', value: 667 },
        { label: 'لومار', value: 668 },
        { label: 'ماژین', value: 669 },
        { label: 'ملکشاهی', value: 87 },
        { label: 'مهران', value: 86 },
        { label: 'مورموری', value: 670 },
        { label: 'موسیان', value: 671 },
        { label: 'میمه', value: 672 },
    ],
    //7 - بوشهر
    [

        { label: 'بوشهر', value: 90 },
        { label: 'آباد', value: 673 },
        { label: 'آب پخش', value: 674 },
        { label: 'آبدان', value: 675 },
        { label: 'امام حسن', value: 676 },
        { label: 'انارستان', value: 677 },
        { label: 'اهرم', value: 678 },
        { label: 'بادوله', value: 679 },
        { label: 'برازجان', value: 436 },
        { label: 'بردخون', value: 680 },
        { label: 'بردستان', value: 681 },
        { label: 'بندر دیر', value: 682 },
        { label: 'بندر دیلم', value: 99 },
        { label: 'بندر ریگ', value: 683 },
        { label: 'بندر سیراف', value: 684 },
        { label: 'بندر عسلویه', value: 685 },
        { label: 'بندر کنگان', value: 92 },
        { label: 'بندر گناوه', value: 93 },
        { label: 'بنک', value: 686 },
        { label: 'بوشکان', value: 687 },
        { label: 'بهارستان', value: 688 },
        { label: 'بیدخون', value: 689 },
        { label: 'تنگ ارم', value: 690 },
        { label: 'جم', value: 97 },
        { label: 'چاه‌مبارک', value: 691 },
        { label: 'چغادک', value: 692 },
        { label: 'خارک', value: 693 },
        { label: 'خورموج', value: 696 },
        { label: 'دالکی', value: 697 },
        { label: 'دشتی', value: 94 },
        { label: 'دلوار', value: 698 },
        { label: 'دوراهک', value: 699 },
        { label: 'ریز', value: 700 },
        { label: 'سعدآباد', value: 701 },
        { label: 'شبانکاره', value: 694 },
        { label: 'شُنبه', value: 702 },
        { label: 'عالی‌شهر', value: 703 },
        { label: 'عسلویه', value: 96 },
        { label: 'کاکی', value: 704 },
        { label: 'کلمه', value: 705 },
        { label: 'نخل تقی', value: 706 },
        { label: 'وحدتیه', value: 707 },
    ],
    //8 - تهران
    [

        { label: 'تهران', value: 100 },
        { label: 'آبسرد', value: 708 },
        { label: 'آبعلی', value: 709 },
        { label: 'احمدآباد مستوفی', value: 710 },
        { label: 'ارجمند', value: 711 },
        { label: 'اسلامشهر', value: 102 },
        { label: 'اندیشه', value: 712 },
        { label: 'باغستان', value: 713 },
        { label: 'باقرشهر', value: 714 },
        { label: 'بومهن', value: 715 },
        { label: 'پاکدشت', value: 105 },
        { label: 'پردیس', value: 111 },
        { label: 'پرند', value: 715 },
        { label: 'پیشوا', value: 113 },
        { label: 'جاجرود', value: 1510 },
        { label: 'جلیل‌آباد (ورامین)', value: 721 },
        { label: 'جوادآباد', value: 717 },
        { label: 'چهاردانگه', value: 718 },
        { label: 'حسن‌آباد', value: 719 },
        { label: 'خسروآباد (پردیس)', value: 720 },
        { label: 'دماوند', value: 112 },
        { label: 'رباط‌کریم', value: 108 },
        { label: 'رودهن', value: 722 },
        { label: 'ری', value: 106 },
        { label: 'سعیدآباد (پردیس)', value: 724 },
        { label: 'شاهدشهر', value: 725 },
        { label: 'شریف‌آباد', value: 726 },
        { label: 'شمشک', value: 727 },
        { label: 'شهریار', value: 101 },
        { label: 'صالحیه', value: 728 },
        { label: 'صباشهر', value: 729 },
        { label: 'صفادشت', value: 730 },
        { label: 'فردوسیه', value: 731 },
        { label: 'فرون آباد', value: 732 },
        { label: 'فشم', value: 733 },
        { label: 'فیروزکوه', value: 115 },
        { label: 'قدس', value: 107 },
        { label: 'قرچک', value: 110 },
        { label: 'قلعه‌نو (ری)', value: 735 },
        { label: 'قیام‌دشت', value: 736 },
        { label: 'کهریزک', value: 737 },
        { label: 'کیلان', value: 738 },
        { label: 'گلستان', value: 739 },
        { label: 'لواسان', value: 740 },
        { label: 'ملارد', value: 104 },
        { label: 'نسیم شهر', value: 741 },
        { label: 'نصیرشهر', value: 742 },
        { label: 'وحیدیه', value: 743 },
        { label: 'ورامین', value: 109 },

    ],
    //9 - چهارمحال و بختیاری
    [

        { label: 'شهرکرد', value: 116 },
        { label: 'آلونی', value: 744 },
        { label: 'اردل', value: 121 },
        { label: 'باباحیدر', value: 745 },
        { label: 'بازفت', value: 746 },
        { label: 'بروجن', value: 118 },
        { label: 'بلداجی', value: 747 },
        { label: 'بن', value: 124 },
        { label: 'پردنجان', value: 748 },
        { label: 'جونقان', value: 749 },
        { label: 'چلگرد', value: 750 },
        { label: 'چلیچه', value: 751 },
        { label: 'دستنا', value: 752 },
        { label: 'دشتک', value: 753 },
        { label: 'سامان', value: 123 },
        { label: 'سرخون', value: 754 },
        { label: 'سردشت', value: 755 },
        { label: 'سفیددشت', value: 756 },
        { label: 'سودجان', value: 757 },
        { label: 'سورشجان', value: 758 },
        { label: 'شلمزار', value: 759 },
        { label: 'شهرکیان', value: 760 },
        { label: 'صمصامی', value: 761 },
        { label: 'طاقانک', value: 762 },
        { label: 'فارسان', value: 119 },
        { label: 'فرادنبه', value: 763 },
        { label: 'فرخ‌شهر', value: 764 },
        { label: 'فیل آباد', value: 765 },
        { label: 'کاج', value: 766 },
        { label: 'گندمان', value: 767 },
        { label: 'گوجان', value: 768 },
        { label: 'گهرو', value: 769 },
        { label: 'لردگان', value: 117 },
        { label: 'مال‌خلیفه', value: 770 },
        { label: 'منج', value: 771 },
        { label: 'ناغان', value: 772 },
        { label: 'نافچ', value: 773 },
        { label: 'نقنه', value: 774 },
        { label: 'وردنجان', value: 775 },
        { label: 'هارونی', value: 776 },
        { label: 'هفشجان', value: 777 },
        { label: 'هوره', value: 778 },
        { label: 'یانچشمه', value: 779 },
    ],


    //10 - خراسان جنوبی
    [

        { label: 'بیرجند', value: 125 },
        { label: 'آبیز', value: 780 },
        { label: 'آرین‌شهر', value: 781 },
        { label: 'آیسک', value: 782 },
        { label: 'ارسک', value: 783 },
        { label: 'اسدیه', value: 784 },
        { label: 'اسفدن', value: 785 },
        { label: 'اسلامیه', value: 786 },
        { label: 'باغستان', value: 787 },
        { label: 'بشرویه', value: 135 },
        { label: 'حاجی‌آباد', value: 788 },
        { label: 'خضری دشت‌بیاض', value: 789 },
        { label: 'خوسف', value: 134 },
        { label: 'درح', value: 791 },
        { label: 'دیهوک', value: 792 },
        { label: 'زهان', value: 793 },
        { label: 'سرایان', value: 133 },
        { label: 'سربیشه', value: 131 },
        { label: 'سه‌قلعه', value: 794 },
        { label: 'شوسف', value: 795 },
        { label: 'طبس', value: 127 },
        { label: 'طبس مسینا', value: 796 },
        { label: 'عشق‌آباد', value: 797 },
        { label: 'فردوس', value: 130 },
        { label: 'قائنات', value: 126 },
        { label: 'قهستان', value: 798 },
        { label: 'گزیک', value: 799 },
        { label: 'ماژان', value: 800 },
        { label: 'مود', value: 801 },
        { label: 'نهبندان', value: 129 },
        { label: 'نیمبلوک', value: 802 },
    ],
    //11 - خراسان رضوی
    [
        { label: 'مشهد', value: 136 },
        { label: 'آلماجق', value: 803 },
        { label: 'احمدآباد صولت', value: 804 },
        { label: 'اسحاق‌آباد', value: 805 },
        { label: 'انابد', value: 806 },
        { label: 'باجگیران', value: 807 },
        { label: 'باخرز', value: 154 },
        { label: 'بار', value: 809 },
        { label: 'بایگ', value: 810 },
        { label: 'بجستان', value: 162 },
        { label: 'بردسکن', value: 149 },
        { label: 'بیدخت', value: 814 },
        { label: 'تایباد', value: 145 },
        { label: 'تربت جام', value: 139 },
        { label: 'تربت حیدریه', value: 140 },
        { label: 'جغتای', value: 158 },
        { label: 'جنت‌آباد', value: 816 },
        { label: 'جنگل', value: 817 },
        { label: 'چاپشلو', value: 818 },
        { label: 'چخماق', value: 819 },
        { label: 'چکنه', value: 820 },
        { label: 'چنار', value: 821 },
        { label: 'چناران', value: 143 },
        { label: 'حسن‌آباد', value: 822 },
        { label: 'حکم‌آباد', value: 823 },
        { label: 'خرو', value: 824 },
        { label: 'خلیل‌آباد', value: 156 },
        { label: 'خواف', value: 144 },
        { label: 'داورزن', value: 163 },
        { label: 'درگز', value: 150 },
        { label: 'درود', value: 825 },
        { label: 'دولت‌آباد', value: 826 },
        { label: 'رادکان', value: 827 },
        { label: 'رباط سنگ', value: 828 },
        { label: 'رشتخوار', value: 829 },
        { label: 'رضویه', value: 830 },
        { label: 'رودآب', value: 831 },
        { label: 'روشناوند', value: 832 },
        { label: 'ریواده', value:  833},
        { label: 'ریوش', value: 834 },
        { label: 'ریوند', value: 835 },
        { label: 'سبزوار', value: 138 },
        { label: 'سده', value: 836 },
        { label: 'سرخس', value: 147 },
        { label: 'سفیدسنگ', value: 837 },
        { label: 'سلامی', value:  838},
        { label: 'سلطان‌آباد', value: 839 },
        { label: 'سمیع‌آباد', value: 840 },
        { label: 'سنگان', value:841  },
        { label: 'سیدآباد', value:842  },
        { label: 'شادمهر', value: 844 },
        { label: 'شامکان', value:  843},
        { label: 'شاندیز', value:  845},
        { label: 'ششتمد', value: 846 },
        { label: 'شهرآباد', value: 847 },
        { label: 'شهرزو', value: 848 },
        { label: 'شهرکهنه', value:849  },
        { label: 'صالح‌آباد', value: 850 },
        { label: 'طرقبه', value: 851 },
        { label: 'عشق‌آباد', value:852  },
        { label: 'فرگ قلعه', value: 853 },
        { label: 'فرهادگرد', value: 855 },
        { label: 'فریمان', value: 146 },
        { label: 'فیروزه', value: 159 },
        { label: 'فیض‌آباد', value:857  },
        { label: 'قاسم‌آباد', value: 858 },
        { label: 'قدمگاه', value: 859 },
        { label: 'قلعه‌نو علیا', value: 860 },
        { label: 'قلندرآباد', value: 861 },
        { label: 'قوچان', value: 141 },
        { label: 'کاخک', value: 862 },
        { label: 'کاریز', value: 863 },
        { label: 'کاشمر', value: 142 },
        { label: 'کدکن', value: 864 },
        { label: 'کلات', value: 161 },
        { label: 'کندر', value: 865 },
        { label: 'گرماب', value: 866 },
        { label: 'گلبهار', value: 867 },
        { label: 'گلمکان', value: 868 },
        { label: 'گناباد', value: 148 },
        { label: 'لطف‌آباد', value: 869 },
        { label: 'مزداوند', value: 870 },
        { label: 'مزرج', value: 871 },
        { label: 'مشکان', value: 872 },
        { label: 'مشهد ریزه', value: 873 },
        { label: 'ملک‌آباد', value: 874 },
        { label: 'نسر', value: 875 },
        { label: 'نشتیفان', value: 876 },
        { label: 'نصرآباد', value: 877 },
        { label: 'نقاب', value:  878},
        { label: 'نوخندان', value: 879 },
        { label: 'نوده انقلاب', value: 880 },
        { label: 'نیشابور', value: 137 },
        { label: 'نیل‌شهر', value: 881 },
        { label: 'همت‌آباد', value: 882 },
        { label: 'یونسی', value: 883 },

    ],
    //12 - خراسان شمالی
    [

        { label: 'بجنورد', value: 164 },
        { label: 'آشخانه', value: 884 },
        { label: 'آوا', value: 885 },
        { label: 'اسفراین', value: 166 },
        { label: 'ایور', value: 886 },
        { label: 'پیش‌قلعه', value: 887 },
        { label: 'تیتکانلو', value: 888 },
        { label: 'جاجرم', value: 170 },
        { label: 'چناران‌شهر', value: 889 },
        { label: 'حصار گرم‌خان', value: 890 },
        { label: 'خانلق', value: 891 },
        { label: 'درق', value: 892 },
        { label: 'راز', value: 893 },
        { label: 'زیارت', value: 984 },
        { label: 'سنخواست', value:  895},
        { label: 'شوقان', value: 896 },
        { label: 'شیروان', value: 165 },
        { label: 'صفی‌آباد', value: 897 },
        { label: 'غلامان', value: 898 },
        { label: 'فاروج', value: 168 },
        { label: 'قاضی', value: 900 },
        { label: 'قوشخانه', value: 901 },
        { label: 'گرمه', value: 171 },
        { label: 'لوجلی', value: 902 },
        { label: 'یکه‌سعود', value: 903 },
    ],
    //13 - خوزستان
    [
        { label: 'اهواز', value: 172 },
        { label: 'آبادان', value: 174 },
        { label: 'آبژدان', value: 904 },
        { label: 'آزادی', value:  905},
        { label: 'ابوحمیظه', value: 906 },
        { label: 'اروندکنار', value: 907 },
        { label: 'الوان', value: 908 },
        { label: 'امیدیه', value: 189 },
        { label: 'اندیمشک', value: 180 },
        { label: 'ایذه', value: 177 },
        { label: 'باغ‌ملک', value: 187 },
        { label: 'باوج', value: 911 },
        { label: 'بستان', value: 912 },
        { label: 'بندر امام خمینی', value:  913},
        { label: 'بندر ماهشهر', value: 175 },
        { label: 'بهبهان', value: 179 },
        { label: 'بیدروبه', value:  914},
        { label: 'ترکالکی', value:  915},
        { label: 'تشان', value:  916},
        { label: 'جایزان', value:  917},
        { label: 'جنت مکان', value: 918 },
        { label: 'چغامیش', value:  919},
        { label: 'چم گلک', value: 920 },
        { label: 'چمران', value:  921},
        { label: 'چویبده', value:  922},
        { label: 'حر', value: 923 },
        { label: 'حسینیه', value:924  },
        { label: 'حمیدیه', value: 192 },
        { label: 'خرمشهر', value: 181 },
        { label: 'دارخوین', value: 925 },
        { label: 'دزآب', value:  926},
        { label: 'دزفول', value: 173 },
        { label: 'دهدز', value:  927},
        { label: 'رامشیر', value: 191 },
        { label: 'رامهرمز', value: 183 },
        { label: 'رفیع', value:  928},
        { label: 'زهره', value: 929 },
        { label: 'سرداران', value: 930 },
        { label: 'سماله', value: 931 },
        { label: 'سوسنگرد', value:932  },
        { label: 'سیاه منصور', value: 933 },
        { label: 'شادگان', value: 182 },
        { label: 'شاوور', value: 934 },
        { label: 'شرافت', value: 935 },
        { label: 'شوش', value: 176 },
        { label: 'شوشتر', value: 178 },
        { label: 'شیبان', value:  936},
        { label: 'صالح شهر', value: 937 },
        { label: 'صالح مشطت', value: 938 },
        { label: 'صفی‌آباد', value: 939 },
        { label: 'صیدون', value: 940 },
        { label: 'قلعه خواجه', value: 941 },
        { label: 'قلعه‌تل', value:  942},
        { label: 'كوت سيدنعيم', value:  934},
        { label: 'گتوند', value: 190 },
        { label: 'گل‌گیر', value: 944 },
        { label: 'گوریه', value:  945},
        { label: 'لالی', value: 196 },
        { label: 'ماهشهر', value: 946 },
        { label: 'مسجدسلیمان', value: 184 },
        { label: 'مشراگه', value: 947 },
        { label: 'منصوریه', value: 948 },
        { label: 'میانرود', value: 949 },
        { label: 'میداوود', value: 950 },
        { label: 'مینوشهر', value: 951 },
        { label: 'ویس', value: 952 },
        { label: 'هفتکل', value: 197 },
        { label: 'هندیجان', value: 195 },
        { label: 'هویزه', value: 194 },
    ],
    //14 - زنجان
    [

        { value: 199, label: "زنجان" },
        { value: 954 , label: "آببر" },
        { value: 201, label: "ابهر" },
        { value: 955, label: "ارمغانخانه" },
        { value: 956, label: "چورزق" },
        { value: 957, label: "حلب" },
        { value: 202, label: "خرمدره" },
        { value: 958, label: "دندی" },
        { value: 959, label: "زرین رود" },
        { value: 960, label: "زرین‌آباد" },
        { value: 961, label: "سجاس" },
        { value: 206, label: "سلطانیه" },
        { value: 962, label: "سهرورد" },
        { value: 963, label: "صایین‌قلعه" },
        { value: 964, label: "قیدار" },
        { value: 966, label: "گرماب" },
        { value: 204, label: "ماه‌نشان" },
        { value: 967, label: "نوربهار" },
        { value: 968, label: "نیک پی" },
        { value:969 , label: "هیدج" },
    ],
    //15 - سمنان
    [
        { value: 207, label: "سمنان" },
        { value: 214, label: "آرادان" },
        { value: 971, label: "امیریه" },
        { value: 972, label: "ایوانکی" },
        { value: 973, label: "بسطام" },
        { value:974 , label: "بیارجمند" },
        { value: 209, label: "دامغان" },
        { value: 975, label: "درجزین" },
        { value: 978, label: "دیباج" },
        { value:976 , label: "رضوان" },
        { value: 977, label: "رویان" },
        { value: 213, label: "سرخه" },
        { value: 208, label: "شاهرود" },
        { value: 979, label: "شهمیرزاد" },
        { value: 980, label: "کلاته" },
        { value:981 , label: "کلاته خیج" },
        { value: 982, label: "کهن‌آباد" },
        { value: 210, label: "گرمسار" },
        { value: 983, label: "مجن" },
        { value: 211, label: "مهدی‌شهر" },
        { value: 212, label: "میامی" },
    ],
    //16 - سیستان و بلوچستان
    [

        { value: 215, label: "زاهدان" },
        { value: 217, label: "ایرانشهر" },
        { value: 986, label: "بمپور" },
        { value:987, label: "تفتان" },
        { value: 216, label: "چابهار" },
        { value: 220, label: "خاش" },
        { value: 988, label: "دشتیاری" },
        { value: 227, label: "دلگان" },
        { value: 219, label: "راسک" },
        { value: 221, label: "زابل" },
        { value: 989, label: "زرآباد" },
        { value: 225, label: "زهک" },
        { value: 218, label: "سراوان" },
        { value: 990, label: "سرباز" },
        { value: 224, label: "سیب و سوران" },
        { value: 230, label: "فنوج" },
        { value: 229, label: "قصرقند" },
        { value: 223, label: "کنارک" },
        { value: 992, label: "گلشن" },
        { value: 993, label: "لاشار" },
        { value: 226, label: "مهرستان" },
        { value: 232, label: "میرجاوه" },
        { value: 222, label: "نیک شهر" },
        { value: 231, label: "نیمروز" },
        { value: 233, label: "هامون" },
        { value: 228, label: "هیرمند" },
    ],
    //17 - فارس
    [

        { value: 234, label: "شیراز" },
        { value: 244, label: "آباده" },
        { value:995 , label: "آباده طشک" },
        { value:996 , label: "ارد" },
        { value: 997, label: "اردکان" },
        { value: 259, label: "ارسنجان" },
        { value: 251, label: "استهبان" },
        { value: 998, label: "اسیر" },
        { value:999 , label: "اشکنان" },
        { value: 1000, label: "افزر" },
        { value: 245, label: "اقلید" },
        { value: 1002, label: "اکبرآباد" },
        { value: 1003, label: "امام‌شهر" },
        { value:1004 , label: "اوز" },
        { value: 1005, label: "اهل" },
        { value: 1006, label: "ایج" },
        { value: 1007, label: "ایزدخواست" },
        { value: 1008, label: "بابامنیر" },
        { value: 1009, label: "باب‌انار" },
        { value: 1011, label: "بنارویه" },
        { value: 256, label: "بوانات" },
        { value:1012 , label: "بهمن" },
        { value: 1013, label: "بیرم" },
        { value: 1014, label: "بیضا" },
        { value: 1015, label: "پاسخن" },
        { value: 1017, label: "جنت‌شهر" },
        { value: 1019, label: "جویم" },
        { value: 1020, label: "جهرم" },
        { value: 1021, label: "چاه‌ورز" },
        { value: 1022, label: "حاجی‌آباد" },
        { value: 1023, label: "حسامی" },
        { value:1024 , label: "حسن‌آباد" },
        { value: 1025, label: "خان زنیان" },
        { value: 1026, label: "خانمین" },
        { value: 1027, label: "خاوران" },
        { value: 1028, label: "خرامه" },
        { value:1029 , label: "خشت" },
        { value: 260, label: "خنج" },
        { value: 1031, label: "خور" },
        { value: 1032, label: "خوزی" },
        { value: 1033, label: "خومه‌زار" },
        { value: 1034, label: "خیرآباد" },
        { value: 1035, label: "خیرگو" },
        { value: 240, label: "داراب" },
        { value: 1036, label: "داریان" },
        { value: 1037, label: "دبیران" },
        { value: 1038, label: "دژکرد" },
        { value: 1039, label: "دوبرجی" },
        { value: 1040, label: "دوزه" },
        { value: 1041, label: "دهرم" },
        { value: 1042, label: "دهکویه" },
        { value: 1043, label: "رامجرد" },
        { value: 1044, label: "رحمت‌آباد" },
        { value:1045 , label: "رستاق" },
        { value: 1046, label: "رونیز" },
        { value: 1047, label: "زاهدشهر" },
        { value: 1048, label: "زرقان" },
        { value: 1049, label: "زنگی‌آباد" },
        { value: 1050 , label: "سده" },
        { value: 261, label: "سروستان" },
        { value: 1051, label: "سعادت‌شهر" },
        { value: 1052, label: "سلطان‌شهر" },
        { value: 1053, label: "سورمق" },
        { value: 1054, label: "سیدان" },
        { value: 1055, label: "ششده" },
        { value: 1056, label: "شهرپیر" },
        { value: 1057, label: "صدرا" },
        { value: 1058, label: "صغاد" },
        { value: 1059, label: "صفاشهر" },
        { value: 1060, label: "طسوج" },
        { value: 1061, label: "علامرودشت" },
        { value: 1062, label: "عمادشهر" },
        { value: 1063, label: "فاروق" },
        { value: 1064, label: "فال" },
        { value: 1065, label: "فتح‌آباد" },
        { value: 1066, label: "فدامی" },
        { value: 257, label: "فراشبند" },
        { value: 239, label: "فسا" },
        { value: 241, label: "فیروزآباد" },
        { value: 1068, label: "قائمیه" },
        { value:1069 , label: "قادرآباد" },
        { value: 1070, label: "قره‌بلاغ" },
        { value: 1071, label: "قطب‌آباد" },
        { value: 1072, label: "قطرویه" },
        { value: 250, label: "قیر" },
        { value: 1073, label: "کارزین" },
        { value: 236, label: "کازرون" },
        { value: 1074, label: "کامفیروز" },
        { value: 1075, label: "کره‌ای" },
        { value: 1076, label: "کنارتخته" },
        { value: 248, label: "کوار" },
        { value: 1077, label: "کوپن" },
        { value: 1078, label: "کوره" },
        { value: 1079, label: "کوهنجان" },
        { value: 254, label: "گراش" },
        { value: 1081, label: "گله‌دار" },
        { value: 1082, label: "لار" },
        { value: 246, label: "لامرد" },
        { value: 1083, label: "لپوئی" },
        { value:1084 , label: "لطیفی" },
        { value: 1085, label: "مادرسلیمان" },
        { value: 1086, label: "مبارک‌آباد" },
        { value: 1087, label: "محمله" },
        { value: 235, label: "مرودشت" },
        { value: 1089, label: "مزایجان" },
        { value:1090 , label: "مشکان" },
        { value: 1091, label: "مصیری" },
        { value: 1092, label: "مظفری" },
        { value: 1093, label: "معزآباد جابری" },
        { value: 252, label: "مهر" },
        { value: 1095, label: "میمند" },
        { value: 1096, label: "نوبندگان" },
        { value: 1097, label: "نوجین" },
        { value: 1098, label: "نودان" },
        { value: 1099, label: "نورآباد" },
        { value: 243, label: "نی ریز" },
        { value: 1100, label: "والاشهر" },
        { value: 1101, label: "وراوی" },
        { value: 1102, label: "هماشهر" },
    ],
    //18 - قزوین
    [

        { value: 263, label: "قزوین" },
        { value:1103 , label: "آبگرم" },
        { value: 268, label: "آبیک" },
        { value: 269, label: "آوج" },
        { value: 1105, label: "ارداق" },
        { value: 1106, label: "اسفرورین" },
        { value:1107 , label: "اقبالیه" },
        { value: 1108, label: "الوند" },
        { value: 267, label: "بوئین‌زهرا" },
        { value: 1109, label: "بیدستان" },
        { value: 265, label: "تاکستان" },
        { value: 1110, label: "خاکعلی" },
        { value: 1111, label: "خرمدشت" },
        { value:1112 , label: "دانسفهان" },
        { value: 1113, label: "رازمیان" },
        { value: 1114, label: "زیاران" },
        { value: 1115, label: "سگزآباد" },
        { value: 1116, label: "سیردان" },
        { value: 1117, label: "شال" },
        { value: 1118, label: "شریفیه" },
        { value: 1119, label: "ضیاءآباد" },
        { value: 1121, label: "عصمت آباد" },
        { value: 1122, label: "قشلاق" },
        { value: 1123, label: "کوهین" },
        { value: 1124, label: "محمدیه" },
        { value: 1125, label: "محمودآباد نمونه" },
        { value: 1126, label: "معلم‌کلایه" },
        { value:1127 , label: "مهرگان" },
        { value: 1128, label: "نرجه" },

    ],
    //19 - قم
    [

        { value: 270, label: "قم" },
        { value: 1129, label: "جعفریه" },
        { value: 1130, label: "دستجرد" },
        { value: 1131, label: "سلفچگان" },
        { value: 1132, label: "قنوات" },
        { value:1133 , label: "کهک" },
    ],
    //20 - کردستان
    [
        { value: 271, label: "سنندج" },
        { value:1134 , label: "آرمرده" },
        { value:1135 , label: "بابارشانی" },
        { value: 274, label: "بانه" },
        { value:1137 , label: "برده رشه" },
        { value: 1138, label: "بلبان‌آباد" },
        { value: 1139, label: "بویین سفلی" },
        { value: 277, label: "بیجار" },
        { value: 1141, label: "پیرتاج" },
        { value: 1142, label: "توپ آغاج" },
        { value: 1143, label: "چناره" },
        { value: 1144, label: "حسین آباد" },
        { value: 1145, label: "دزج" },
        { value: 1146, label: "دلبران" },
        { value: 279, label: "دهگلان" },
        { value: 278, label: "دیواندره" },
        { value:1147 , label: "زرینه" },
        { value: 280, label: "سروآباد" },
        { value: 1148, label: "سریش‌آباد" },
        { value: 272, label: "سقز" },
        { value: 1149, label: "سنته" },
        { value: 1150, label: "شویشه" },
        { value: 1151, label: "صاحب" },
        { value: 275, label: "قروه" },
        { value: 276, label: "کامیاران" },
        { value: 1152, label: "کانی سور" },
        { value: 1153, label: "کانی‌دینار" },
        { value: 1154, label: "مالوجه" },
        { value: 273, label: "مریوان" },
        { value: 1155, label: "موچش" },
        { value: 1156, label: "هزارکانیان" },
        { value:1157 , label: "هورامان تخت" },
        { value: 1158, label: "یاسوکند" },
    ],
    //21 - کرمان
    [

        { value: 281, label: "کرمان" },
        { value: 1166, label: "اختیارآباد" },
        { value: 299, label: "ارزوئیه" },
        { value: 1168, label: "امین شهر" },
        { value: 300, label: "انار" },
        { value: 1169, label: "اندوهجرد" },
        { value: 1170, label: "باغین" },
        { value: 291, label: "بافت" },
        { value: 293, label: "بردسیر" },
        { value: 1159, label: "بروات" },
        { value: 1171, label: "بزنجان" },
        { value: 1172, label: "بلورد" },
        { value: 1173, label: "بلوک" },
        { value: 285, label: "بم" },
        { value: 1174, label: "بهرمان" },
        { value: 1175, label: "پاریز" },
        { value: 1176, label: "جبالبارز" },
        { value: 1177, label: "جوادیه الهیه" },
        { value: 1178, label: "جوپار" },
        { value: 1179, label: "جوزم" },
        { value: 284, label: "جیرفت" },
        { value:1180 , label: "چاه دادخدا" },
        { value: 1181, label: "چاه مرید" },
        { value: 1182, label: "چترود" },
        { value: 1183, label: "حور پاسفید" },
        { value: 1184, label: "خاتون آباد" },
        { value: 1185, label: "خانوک" },
        { value: 1186, label: "خورسند" },
        { value: 1187, label: "درب بهشت" },
        { value: 1188, label: "دشتکار" },
        { value: 1189, label: "دوساری" },
        { value: 1190, label: "دهج" },
        { value: 1191, label: "دهکهان" },
        { value: 1192, label: "دهنو اسلام آباد" },
        { value: 301, label: "رابر" },
        { value: 298, label: "راور" },
        { value: 1193, label: "رحمت آباد" },
        { value: 283, label: "رفسنجان" },
        { value: 1194, label: "رمشک" },
        { value: 1195, label: "رودبار" },
        { value:1196 , label: "ریحان" },
        { value: 286, label: "زرند" },
        { value: 1197, label: "زنگی‌آباد" },
        { value: 1198, label: "زهکلوت" },
        { value: 1199, label: "زیدآباد" },
        { value: 282, label: "سیرجان" },
        { value: 1201, label: "سیریز" },
        { value: 1202, label: "شهداد" },
        { value: 288, label: "شهربابک" },
        { value: 1204, label: "صفاییه" },
        { value: 1205, label: "عباس آباد سردار" },
        { value: 1206, label: "علی‌آباد" },
        { value: 292, label: "عنبرآباد" },
        { value: 302, label: "فاریاب" },
        { value: 295, label: "فهرج" },
        { value:1207 , label: "فیض اباد" },
        { value: 294, label: "قلعه گنج" },
        { value: 1208, label: "کاظم آباد" },
        { value: 1209, label: "کشکوئیه" },
        { value: 303, label: "کوهبنان" },
        { value: 289, label: "کهنوج" },
        { value: 1210, label: "کیانشهر" },
        { value: 1211, label: "گلباف" },
        { value: 1212, label: "گلزار" },
        { value: 1213, label: "گنبکی" },
        { value: 1214, label: "لاله زار" },
        { value: 1163, label: "ماهان" },
        { value: 1161, label: "محمدآباد" },
        { value:1215 , label: "محی آباد" },
        { value: 1216, label: "مردهک" },
        { value: 1217, label: "مس سرچشمه" },
        { value: 296, label: "منوجان" },
        { value: 1162, label: "نجف شهر" },
        { value: 297, label: "نرماشیر" },
        { value: 1219, label: "نظام شهر" },
        { value:1220 , label: "نگار" },
        { value:1221 , label: "نودژ" },
        { value: 1222, label: "هجدک" },
        { value: 1223, label: "هماشهر" },
        { value: 1224, label: "هنزا" },
        { value: 1225, label: "یزدان شهر" },
    ],
    //22 - کرمانشاه
    [

        { value: 304, label: "کرمانشاه" },
        { value: 305, label: "اسلام‌آباد غرب" },
        { value: 1226, label: "بانه‌وره" },
        { value: 1227, label: "باینگان" },
        { value: 1228, label: "بیستون" },
        { value: 312, label: "پاوه" },
        { value: 1229, label: "تازه‌آباد" },
        { value: 310, label: "جوانرود" },
        { value:1230 , label: "حمیل" },
        { value:1231 , label: "رباط" },
        { value: 314, label: "روانسر" },
        { value: 1232, label: "ریجاب" },
        { value: 306, label: "سرپل ذهاب" },
        { value:1233 , label: "سرمست" },
        { value: 1234, label: "سطر" },
        { value: 307, label: "سنقر" },
        { value: 1235, label: "سومار" },
        { value: 1236, label: "شاهو" },
        { value: 1237, label: "شروینه" },
        { value: 311, label: "صحنه" },
        { value: 317, label: "قصرشیرین" },
        { value: 1238, label: "قلعه" },
        { value: 1239, label: "کرند غرب" },
        { value: 309, label: "کنگاور" },
        { value: 1240, label: "کوزران" },
        { value: 1241, label: "گودین" },
        { value: 1242, label: "گهواره" },
        { value: 313, label: "گیلانغرب" },
        { value: 1243, label: "میان راهان" },
        { value: 1244, label: "میرآباد" },
        { value: 1245, label: "نودشه" },
        { value: 1246, label: "نوسود" },
        { value: 308, label: "هرسین" },
        { value: 1247, label: "هلشی" },
    ],
    //23 - کهگیلویه و بویراحمد
    [

        { value: 434, label: "یاسوج" },
        { value: 325, label: "باشت" },
        { value: 1249, label: "بوستان" },
        { value: 1250, label: "پاتاوه" },
        { value: 323, label: "چرام" },
        { value: 1251, label: "چیتاب" },
        { value:1252 , label: "دوگنبدان" },
        { value: 1253, label: "دهدشت" },
        { value: 1254, label: "دیشموک" },
        { value:1255 , label: "سپیدار" },
        { value:1256 , label: "سرآسیاب یوسفی" },
        { value:1257 , label: "سرفاریاب" },
        { value:1258 , label: "سوق" },
        { value: 1259, label: "سی‌سخت" },
        { value: 1260, label: "قلعه رئیسی" },
        { value: 1261, label: "قلعه ممبی" },
        { value: 320, label: "گچساران" },
        { value: 1262, label: "گراب سفلی" },
        { value: 324, label: "لنده" },
        { value: 1263, label: "لیکک" },
        { value: 1264, label: "مادوان" },
        { value: 1265, label: "مارگون" },
    ],
    //24 - گلستان
    [
        { value: 326, label: "گرگان" },
        { value: 331, label: "آزادشهر" },
        { value: 329, label: "آق‌قلا" },
        { value: 1269, label: "انبارآلوم" },
        { value: 1270, label: "اینچه‌برون" },
        { value: 1271, label: "بندر ترکمن" },
        { value: 339, label: "بندر گز" },
        { value: 1272, label: "تاتار علیا" },
        { value: 1273, label: "جلین" },
        { value: 1274, label: "خان‌ببین" },
        { value: 1275, label: "دوزین" },
        { value: 332, label: "رامیان" },
        { value:1277 , label: "سرخنکلاته" },
        { value: 1278, label: "سنگدوین" },
        { value: 1279, label: "سیمین‌شهر" },
        { value: 1280, label: "صادق‌آباد" },
        { value: 328, label: "علی‌آباد" },
        { value: 1281, label: "فاضل‌آباد" },
        { value: 1282, label: "فراغی" },
        { value: 1283, label: "قرق" },
        { value: 335, label: "کردکوی" },
        { value: 1285, label: "کرند" },
        { value: 330, label: "کلاله" },
        { value: 337, label: "گالیکش" },
        { value:1287 , label: "گلیداغ" },
        { value: 336, label: "گمیشان" },
        { value: 327, label: "گنبد کاووس" },
        { value:1289 , label: "مراوه" },
        { value:1290 , label: "مزرعه" },
        { value: 334, label: "مینودشت" },
        { value:1292 , label: "نگین‌شهر" },
        { value: 1293, label: "نوده خاندوز" },
        { value: 1294, label: "نوکنده" },
    ],
    //25 - گیلان
    [
        { value: 340, label: "رشت" },
        { value: 350, label: "آستارا" },
        { value: 347, label: "آستانه اشرفیه" },
        { value: 1295, label: "اتاقور" },
        { value:1296 , label: "احمدسرگوراب" },
        { value: 1297, label: "اسالم" },
        { value: 355, label: "املش" },
        { value: 1298, label: "بازارجمعه" },
        { value: 345, label: "بندر انزلی" },
        { value: 1299, label: "پره‌سر" },
        { value: 1300, label: "پیربازار" },
        { value: 1301, label: "توتکابن" },
        { value: 1302, label: "جیرنده" },
        { value:1303 , label: "چابکسر" },
        { value: 1304, label: "چاف و چمخاله" },
        { value: 1305, label: "چوبر" },
        { value: 1306, label: "حویق" },
        { value: 1307, label: "خشکبیجار" },
        { value: 1308, label: "خمام" },
        { value: 1309, label: "دیلمان" },
        { value: 1310, label: "رانکوه" },
        { value:1311 , label: "رحیم‌آباد" },
        { value: 1312, label: "رستم‌آباد" },
        { value: 351, label: "رضوانشهر" },
        { value: 348, label: "رودبار" },
        { value: 1313, label: "رودبنه" },
        { value: 343, label: "رودسر" },
        { value: 1314, label: "سنگر" },
        { value: 354, label: "سیاهکل" },
        { value: 352, label: "شفت" },
        { value: 1316, label: "شلمان" },
        { value: 346, label: "صومعه‌سرا" },
        { value: 1317, label: "ضیابر" },
        { value: 349, label: "فومن" },
        { value: 1318, label: "کلاچای" },
        { value: 1319, label: "کوچصفهان" },
        { value: 1320, label: "کومله" },
        { value: 1321, label: "کیاشهر" },
        { value: 1322, label: "گوراب زرمیخ" },
        { value: 342, label: "لاهیجان" },
        { value:1323 , label: "لشت نشا" },
        { value: 344, label: "لنگرود" },
        { value: 1324, label: "لوشان" },
        { value: 1325, label: "لولمان" },
        { value: 1326, label: "لوندویل" },
        { value: 1327, label: "لیسار" },
        { value: 353, label: "ماسال" },
        { value: 1328, label: "ماسوله" },
        { value: 1329, label: "ماکلوان" },
        { value: 1330, label: "مرجغل" },
        { value: 1331, label: "منجیل" },
        { value: 1332, label: "واجارگاه" },
        { value: 1333, label: "هشتپر" },
    ],
    //26 - لرستان
    [

        { value: 356, label: "خرم‌آباد" },
        { value: 363, label: "ازنا" },
        { value: 1334, label: "اشترینان" },
        { value: 1335, label: "الشتر" },
        { value: 361, label: "الیگودرز" },
        { value: 1336, label: "برخوردار" },
        { value: 357, label: "بروجرد" },
        { value: 1337, label: "بیران‌شهر" },
        { value: 364, label: "پلدختر" },
        { value: 1339, label: "تیتکان" },
        { value: 1340, label: "چالانچولان" },
        { value: 1341, label: "چقابل" },
        { value: 1342, label: "چم پلک" },
        { value: 1343, label: "چمن سلطان" },
        { value: 1344, label: "درب گنبد" },
        { value: 358, label: "دورود" },
        { value: 1345, label: "زاغه" },
        { value: 1346, label: "سپیددشت" },
        { value: 1347, label: "سراب حمام" },
        { value: 1348, label: "سراب دوره" },
        { value: 1349, label: "شاهپورآباد" },
        { value: 1350, label: "شول‌آباد" },
        { value: 1351, label: "فیروزآباد" },
        { value: 1352, label: "کونانی" },
        { value: 359, label: "کوهدشت" },
        { value: 1353, label: "گراب" },
        { value: 1354, label: "مؤمن‌آباد" },
        { value: 1355, label: "معمولان" },
        { value: 1356, label: "نورآباد" },
        { value: 1357, label: "ونایی" },
        { value: 1358, label: "ویسیان" },
        { value: 1359, label: "هفت چشمه" },
    ],
    //27 - مازندران
    [

        { value: 367, label: "ساری" },
        { value: 1360, label: "آستانه نو" },
        { value: 1361, label: "آکند" },
        { value: 1362, label: "آلاشت" },
        { value: 369, label: "آمل" },
        { value:1363 , label: "اجبارکلا" },
        { value: 1364, label: "ارطه" },
        { value: 1365, label: "امامزاده عبدالله" },
        { value: 1366, label: "امیرکلا" },
        { value: 1367, label: "ایزدشهر" },
        { value: 368, label: "بابل" },
        { value: 374, label: "بابلسر" },
        { value: 1368, label: "بلده" },
        { value: 371, label: "بهشهر" },
        { value: 1369, label: "بهنمیر" },
        { value: 1370, label: "پایین هولار" },
        { value: 1371, label: "پل سفید" },
        { value: 1372, label: "پول" },
        { value: 372, label: "تنکابن" },
        { value: 379, label: "جویبار" },
        { value: 377, label: "چالوس" },
        { value: 1373, label: "چمستان" },
        { value:1374 , label: "خلیل شهر" },
        { value: 1375, label: "خوش‌رودپی" },
        { value: 1376, label: "دابودشت" },
        { value: 380, label: "رامسر" },
        { value: 1377, label: "رستمکلا" },
        { value: 1378, label: "رویان" },
        { value: 1379, label: "رینه" },
        { value: 1380, label: "زرگر" },
        { value: 1381, label: "زیرآب" },
        { value: 1382, label: "سرخرود" },
        { value: 1383, label: "سلمان‌شهر" },
        { value: 1384, label: "سورک" },
        { value: 1385, label: "شیرگاه" },
        { value: 1386, label: "شیرود" },
        { value: 1387, label: "طبقده" },
        { value: 383, label: "عباس‌آباد" },
        { value: 1388, label: "فرح آباد" },
        { value: 381, label: "فریدونکنار" },
        { value: 1389, label: "فریم" },
        { value: 370, label: "قائم‌شهر" },
        { value: 1390, label: "کتالم وسادات شهر" },
        { value: 1391, label: "کجور" },
        { value: 1392, label: "کلارآباد" },
        { value: 386, label: "کلاردشت" },
        { value: 1394, label: "کوهی‌خیل" },
        { value: 1395, label: "کیاسر" },
        { value: 1396, label: "کیاکلا" },
        { value: 1397, label: "گتاب" },
        { value: 1398, label: "گزنک" },
        { value: 385, label: "گلوگاه" },
        { value: 378, label: "محمودآباد" },
        { value: 1400, label: "مرزن‌آباد" },
        { value: 1401, label: "مرزیکلا" },
        { value: 1402, label: "نشتارود" },
        { value: 376, label: "نکا" },
        { value: 375, label: "نور" },
        { value: 373, label: "نوشهر" },
        { value: 1404, label: "هادی‌شهر" },
        { value: 1405, label: "هچیرود" },
    ],
    //28 - مرکزی
    [

        { value: 388, label: "اراک" },
        { value: 399, label: "آشتیان" },
        { value: 1407, label: "پرندک" },
        { value: 398, label: "تفرش" },
        { value:1408 , label: "توره" },
        { value: 1409, label: "جاورسیان" },
        { value: 1410, label: "خشکرود" },
        { value: 391, label: "خمین" },
        { value: 1411, label: "خنجین" },
        { value: 394, label: "خنداب" },
        { value: 1412, label: "داودآباد" },
        { value: 395, label: "دلیجان" },
        { value: 1413, label: "رازقان" },
        { value: 1414, label: "زاویه" },
        { value: 1415, label: "ساروق" },
        { value: 389, label: "ساوه" },
        { value: 1416, label: "سنجان" },
        { value: 390, label: "شازند" },
        { value:1417 , label: "شهباز" },
        { value:1418 , label: "غرق آباد" },
        { value: 1419, label: "فرمهین" },
        { value: 1420, label: "قورچی باشی" },
        { value: 1421, label: "کارچان" },
        { value: 1422, label: "کرهرود" },
        { value: 396, label: "کمیجان" },
        { value: 1424, label: "مأمونیه" },
        { value: 393, label: "محلات" },
        { value: 1425, label: "مهاجران" },
        { value: 1426, label: "میلاجرد" },
        { value: 1427, label: "نراق" },
        { value: 1428, label: "نوبران" },
        { value: 1429, label: "نیمور" },
        { value: 1430, label: "هندودر" },
    ],
    //29 - هرمزگان
    [

        { value: 400, label: "بندرعباس" },
        { value: 412, label: "ابوموسی" },
        { value: 405, label: "بستک" },
        { value: 1432, label: "بندر پل" },
        { value: 407, label: "بندر جاسک" },
        { value: 408, label: "بندر خمیر" },
        { value: 1434, label: "بندر کنگ" },
        { value: 402, label: "بندر لنگه" },
        { value: 1435, label: "بندزرک" },
        { value: 1436, label: "بیکا" },
        { value: 409, label: "پارسیان" },
        { value: 1437, label: "تازیان پایین" },
        { value: 1438, label: "تخت" },
        { value: 1439, label: "تیرور" },
        { value: 1440, label: "جناح" },
        { value: 406, label: "حاجی‌آباد" },
        { value: 1441, label: "درگهان" },
        { value: 1442, label: "دشتی" },
        { value: 1443, label: "دهبارز" },
        { value: 1444, label: "رمکان" },
        { value: 1445, label: "رویدر" },
        { value: 1446, label: "زهوکی" },
        { value: 1447, label: "زیارتعلی" },
        { value: 1448, label: "سردشت" },
        { value: 1449, label: "سرگز" },
        { value: 1450, label: "سندرک" },
        { value: 1451, label: "سوزا" },
        { value: 410, label: "سیریک" },
        { value: 1452, label: "طبل" },
        { value: 1453, label: "فارغان" },
        { value: 1454, label: "فین" },
        { value: 403, label: "قشم" },
        { value: 1455, label: "قلعه قاضی" },
        { value: 1456, label: "کرگان" },
        { value: 1457, label: "کوخردهرنگ" },
        { value: 1458, label: "کوشکنار" },
        { value: 1459, label: "کوهستک" },
        { value: 1460, label: "کوهیج" },
        { value: 432, label: "کیش" },
        { value: 1461, label: "گروک" },
        { value: 1462, label: "گوهران" },
        { value: 1463, label: "لافت" },
        { value: 1464, label: "لمزان" },
        { value: 1465, label: "لیردف" },
        { value: 401, label: "میناب" },
        { value: 1466, label: "هرمز" },
        { value: 1467, label: "هشت‌بندی" },
        { value: 1468, label: "هنگویه" },
    ],
    //30 - همدان
    [
        { value: 413, label: "همدان" },
        { value: 1469, label: "ازندریان" },
        { value: 420, label: "اسدآباد" },
        { value: 1471, label: "اسلام‌شهر آق‌گل" },
        { value:1472 , label: "آجین" },
        { value:1473 , label: "برزول" },
        { value: 417, label: "بهار" },
        { value: 419, label: "تویسرکان" },
        { value: 1474, label: "جورقان" },
        { value: 1475, label: "جوکار" },
        { value: 1476, label: "دمق" },
        { value: 418, label: "رزن" },
        { value: 1477, label: "زنگنه" },
        { value: 1478, label: "سامن" },
        { value: 1479, label: "سرکان" },
        { value: 1480, label: "شیرین‌سو" },
        { value: 1481, label: "صالح آباد" },
        { value: 421, label: "فامنین" },
        { value: 1483, label: "فرسفج" },
        { value: 1484, label: "فیروزان" },
        { value: 1485, label: "قروه درجزین" },
        { value: 1486, label: "قهاوند" },
        { value: 416, label: "کبودرآهنگ" },
        { value: 1487, label: "گل‌تپه" },
        { value: 1488, label: "گیان" },
        { value: 1489, label: "لالجین" },
        { value: 1490, label: "مریانج" },
        { value: 414, label: "ملایر" },
        { value: 1491, label: "مهاجران" },
        { value: 415, label: "نهاوند" },
    ],
    //31 - یزد
    [

        { value: 422, label: "یزد" },
        { value: 426, label: "ابرکوه" },
        { value: 1492, label: "احمدآباد" },
        { value: 424, label: "اردکان" },
        { value: 430, label: "اشکذر" },
        { value: 427, label: "بافق" },
        { value: 1493, label: "بخ" },
        { value: 1494, label: "بفروئیه" },
        { value: 431, label: "بهاباد" },
        { value: 428, label: "تفت" },
        { value: 1495, label: "خرانق" },
        { value: 1496, label: "خضرآباد" },
        { value: 1497, label: "زارچ" },
        { value: 1498, label: "عقدا" },
        { value: 1499, label: "مروست" },
        { value: 1502, label: "مهردشت" },
        { value: 425, label: "مهریز" },
        { value: 423, label: "میبد" },
        { value: 1500, label: "ندوشن" },
        { value: 1503, label: "نیر" },
        { value: 1504, label: "هرات" }
    ],
];
export default CityArray;