const CharArray=[
    { label: 'الف', value: 'الف' },
    { label: 'ب', value: 'ب' },
    { label: 'پ', value: 'پ' },
    { label: 'ت', value: 'ت' },
    { label: 'ث', value: 'ث' },
    { label: 'ج', value: 'ج' },
    { label: 'چ', value: 'چ' },
    { label: 'ح', value: 'ح' },
    { label: 'خ', value: 'خ' },
    { label: 'د', value: 'د' },
    { label: 'ذ', value: 'ذ' },
    { label: 'ر', value: 'ر' },
    { label: 'ز', value: 'ز' },
    { label: 'ژ', value: 'ژ' },
    { label: 'س', value: 'س' },
    { label: 'ش', value: 'ش' },
    { label: 'ص', value: 'ص' },
    { label: 'ض', value: 'ض' },
    { label: 'ط', value: 'ط' },
    { label: 'ظ', value: 'ظ' },
    { label: 'ع', value: 'ع' },
    { label: 'غ', value: 'غ' },
    { label: 'ف', value: 'ف' },
    { label: 'ق', value: 'ق' },
    { label: 'ک', value: 'ک' },
    { label: 'گ', value: 'گ' },
    { label: 'ل', value: 'ل' },
    { label: 'م', value: 'م' },
    { label: 'ن', value: 'ن' },
    { label: 'و', value: 'و' },
    { label: 'ه', value: 'ه' },
    { label: 'ی', value: 'ی' },
];

export default CharArray;